# Generated by Django 3.2.5 on 2022-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='cangku_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='dingdanzhuangtai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
