# Generated by Django 3.2.13 on 2022-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_content', models.CharField(max_length=2000)),
                ('user_score', models.FloatField(max_length=2)),
                ('user_time', models.DateField()),
            ],
        ),
    ]
