# Generated by Django 3.2.5 on 2022-06-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20220607_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuancailiao',
            name='gongyingshang_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yuancailiao',
            name='yuancailiao_max',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='baozhiqi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='cangku_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='chandi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='gongyingshang_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='shengchanriqi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='yuancailiao_danjia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='yuancailiao_zhiliang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuancailiao',
            name='yuancailiao_zhonglei',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
