# Generated by Django 3.2.5 on 2022-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20220607_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='caigoudingdan',
            name='caigoushijian',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='caigoudingdan',
            name='dingdanxiangqing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caigoudingdan',
            name='dingdanzhuangtai',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caigoudingdan',
            name='fuzeren',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caigoudingdan',
            name='pingzheng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shangpin',
            name='shuliang',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='dingdanxiangqing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='pingzhengbianhao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='xiadanzhanghu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='shangpin_zhonglei',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='dingdanzhuangtai',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
