# Generated by Django 3.2.5 on 2022-06-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rewards'),
        ('homepage', '0005_auto_20220607_1456'),
    ]

    operations = [
    ]
