# Generated by Django 3.2.5 on 2022-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_merge_0002_rewards_0005_auto_20220607_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuangong',
            name='bumen_mingcheng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yuangong',
            name='yuangong_nianling',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
