# Generated by Django 3.2.5 on 2022-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_yuangong_yuangong_zhuangtai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuangong',
            name='bumen_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='shenfenzhenghao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='yuangong_dianhua',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='yuangong_xinchou',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='yuangong_xingbie',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='yuangong_xingming',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuangong',
            name='yuangong_zhiwei',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
