# Generated by Django 3.2.5 on 2022-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20220611_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='gongyingshang',
            name='gongyingshang_jingdu',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gongyingshang',
            name='gongyingshang_weidu',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gongyingshang',
            name='gongyingshang_dianhua',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gongyingshang',
            name='gongyingshang_dizhi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gongyingshang',
            name='gongyingshang_mingcheng',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
