# Generated by Django 3.2.5 on 2022-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20220612_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhichu',
            fields=[
                ('zhichu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('caigou_id', models.CharField(max_length=20)),
                ('gongyingshang_id', models.CharField(max_length=20)),
                ('zhichu_shijian', models.DateField()),
                ('zongjine', models.FloatField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='shouru',
            old_name='shouru_shijain',
            new_name='shouru_shijian',
        ),
        migrations.AddField(
            model_name='cangku',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cangku',
            name='longitu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shouru',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shouru',
            name='zongjine',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yuancailiao',
            name='yuancailiao_mingcheng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='dingdanbeizhu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='peisongweizhi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='peisongyuan_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shangpin_goumaishuliang',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shangpin_zongjia',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shouhuodizhi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shouhuorenlianxi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shouhuorenxingming',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='shourujilu_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='xiaoshou_zongjine',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
