# Generated by Django 3.2.5 on 2022-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20220612_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cangku',
            name='cangku_manager',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shangpin',
            name='suoshudingdan_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shangpin',
            name='suoshugongyingshang_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
