# Generated by Django 3.2.5 on 2022-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20220612_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='cangku_jingdu',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='cangku_weidu',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='mudidi_jingdu',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaoshoudingdan',
            name='mudidi_weidu',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
