# Generated by Django 3.2.5 on 2022-06-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20220612_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='songdashijian',
            field=models.DateTimeField(null=True),
        ),
    ]
