# Generated by Django 3.2.5 on 2022-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_xiaoshoudingdan_songdashijian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caigoudingdan',
            name='caigou_zongjine',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caigoudingdan',
            name='gongyingshang_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caigoudingdan',
            name='huopinshuliang',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='caigoudingdan',
            name='huopinzongjia',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
