# Generated by Django 3.2.5 on 2022-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20220612_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='caigoudingdan',
            name='yuancailiao_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caigoudingdan',
            name='yuancailiao_shuliang',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
