# Generated by Django 3.2.5 on 2022-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20220612_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caigoudingdan',
            name='yuqidaohuoshijian',
            field=models.DateField(null=True),
        ),
    ]
