# Generated by Django 3.2.5 on 2022-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_caigoudingdan_yuqidaohuoshijian'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangpin',
            name='yuancailiao_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
