# Generated by Django 3.2.5 on 2022-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20220612_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangpin',
            name='shanpin_chandi_latitude',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shangpin',
            name='shanpin_chandi_longitude',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
