# Generated by Django 3.2.5 on 2022-06-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20220612_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaoshoudingdan',
            name='peisongweizhi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
